-- Supabase-backed tables for the existing frontend/backend API contract.
-- These tables intentionally mirror the demo API models, while the older
-- participant/volunteer/donor tables remain available under /api/supabase.

CREATE TABLE IF NOT EXISTS public.households (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    carer_person_id BIGINT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS public.people (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    role_primary TEXT NOT NULL DEFAULT 'family',
    roles TEXT NOT NULL DEFAULT 'family',
    language TEXT NOT NULL DEFAULT 'both',
    phone TEXT,
    profile_code TEXT NOT NULL UNIQUE,
    household_role TEXT,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    household_id BIGINT REFERENCES public.households(id) ON DELETE SET NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'households_carer_person_id_fkey'
    ) THEN
        ALTER TABLE public.households
            ADD CONSTRAINT households_carer_person_id_fkey
            FOREIGN KEY (carer_person_id) REFERENCES public.people(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.comm_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL UNIQUE REFERENCES public.people(id) ON DELETE CASCADE,
    email_on BOOLEAN NOT NULL DEFAULT TRUE,
    sms_on BOOLEAN NOT NULL DEFAULT FALSE,
    whatsapp_on BOOLEAN NOT NULL DEFAULT FALSE,
    opt_out_token TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    goal TEXT NOT NULL,
    age_band TEXT NOT NULL,
    day TEXT NOT NULL,
    support_need TEXT NOT NULL,
    language TEXT NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 10,
    spots_left INTEGER NOT NULL DEFAULT 10,
    location TEXT NOT NULL DEFAULT 'San Po Kong'
);

CREATE TABLE IF NOT EXISTS public.registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES public.activities(id) ON DELETE CASCADE,
    household_id BIGINT NOT NULL REFERENCES public.households(id) ON DELETE CASCADE,
    member_person_id BIGINT NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'registered',
    waitlist_position INTEGER,
    reminder_channel TEXT NOT NULL DEFAULT 'email',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    session_date DATE,
    feedback TEXT,
    feedback_at TIMESTAMPTZ,
    CONSTRAINT uq_reg_activity_member UNIQUE (activity_id, member_person_id)
);

CREATE TABLE IF NOT EXISTS public.achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_person_id BIGINT NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    pillar TEXT NOT NULL DEFAULT 'sport',
    status TEXT NOT NULL DEFAULT 'pending',
    share_consent BOOLEAN NOT NULL DEFAULT FALSE,
    coach_name TEXT NOT NULL DEFAULT 'Coach Pat',
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_person_id BIGINT NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'in_progress',
    target_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.donation_commitments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supporter_person_id BIGINT NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
    amount_hkd NUMERIC(12, 2) NOT NULL,
    fund_category TEXT NOT NULL DEFAULT 'Sports programmes',
    status TEXT NOT NULL DEFAULT 'active',
    cadence TEXT NOT NULL DEFAULT 'monthly',
    office_perk_unlocked BOOLEAN NOT NULL DEFAULT TRUE,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.donation_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commitment_id BIGINT NOT NULL REFERENCES public.donation_commitments(id) ON DELETE CASCADE,
    amount_hkd NUMERIC(12, 2) NOT NULL,
    paid_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    story_back TEXT
);

CREATE TABLE IF NOT EXISTS public.impact_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
    title TEXT NOT NULL DEFAULT 'Local contributor',
    level TEXT NOT NULL DEFAULT 'bronze',
    earned_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.volunteer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL UNIQUE REFERENCES public.people(id) ON DELETE CASCADE,
    skills TEXT NOT NULL DEFAULT '',
    languages TEXT NOT NULL DEFAULT 'en',
    availability TEXT NOT NULL DEFAULT '',
    onboarded BOOLEAN NOT NULL DEFAULT FALSE,
    hours_logged NUMERIC(8, 2) NOT NULL DEFAULT 0,
    points_balance INTEGER NOT NULL DEFAULT 0,
    points_spent INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.volunteer_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    duration_min INTEGER NOT NULL DEFAULT 60,
    skills_needed TEXT NOT NULL DEFAULT '',
    language TEXT NOT NULL DEFAULT 'en',
    remote BOOLEAN NOT NULL DEFAULT TRUE,
    spots_left INTEGER NOT NULL DEFAULT 5,
    requires_onboarding BOOLEAN NOT NULL DEFAULT FALSE,
    scheduled_date DATE
);

CREATE TABLE IF NOT EXISTS public.volunteer_shift_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id BIGINT NOT NULL REFERENCES public.volunteer_shifts(id) ON DELETE CASCADE,
    volunteer_profile_id BIGINT NOT NULL REFERENCES public.volunteer_profiles(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'claimed',
    hours NUMERIC(8, 2) NOT NULL DEFAULT 0,
    reflection TEXT,
    claimed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    points_awarded INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_shift_volunteer UNIQUE (shift_id, volunteer_profile_id)
);

CREATE TABLE IF NOT EXISTS public.hire_enquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT REFERENCES public.people(id) ON DELETE SET NULL,
    creator_label TEXT NOT NULL,
    preferred_date TEXT,
    status TEXT NOT NULL DEFAULT 'received',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.journey_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    channel TEXT NOT NULL DEFAULT 'email',
    payload TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_people_household_id ON public.people(household_id);
CREATE INDEX IF NOT EXISTS idx_registrations_household_id ON public.registrations(household_id);
CREATE INDEX IF NOT EXISTS idx_commitments_supporter ON public.donation_commitments(supporter_person_id);
CREATE INDEX IF NOT EXISTS idx_claims_profile ON public.volunteer_shift_claims(volunteer_profile_id);
CREATE INDEX IF NOT EXISTS idx_journey_person ON public.journey_events(person_id);

ALTER TABLE public.households ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.people ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comm_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donation_commitments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donation_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.impact_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.volunteer_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.volunteer_shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.volunteer_shift_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hire_enquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journey_events ENABLE ROW LEVEL SECURITY;

INSERT INTO public.households (id, name, notes)
VALUES (1, 'Chen family', 'Demo household')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, notes = EXCLUDED.notes;

INSERT INTO public.people
    (id, email, name, role_primary, roles, language, profile_code, household_id, household_role)
VALUES
    (1, 'carer@chen.demo', 'Jamie Chen', 'family', 'family,volunteer,donor', 'both', 'L21-HK-1001', 1, 'mom'),
    (2, 'alex@chen.demo', 'Alex Chen', 'member', 'member', 'yue', 'L21-HK-1002', 1, 'child'),
    (3, 'dad@chen.demo', 'Chris Chen', 'family', 'family,donor', 'en', 'L21-HK-1003', 1, 'dad'),
    (4, 'donor@demo.love21', 'Sam Wong', 'donor', 'donor,volunteer', 'en', 'L21-HK-2001', NULL, NULL),
    (5, 'volunteer@demo.love21', 'Taylor Ng', 'volunteer', 'volunteer,donor', 'both', 'L21-HK-3001', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    name = EXCLUDED.name,
    role_primary = EXCLUDED.role_primary,
    roles = EXCLUDED.roles,
    language = EXCLUDED.language,
    profile_code = EXCLUDED.profile_code,
    household_id = EXCLUDED.household_id,
    household_role = EXCLUDED.household_role;

UPDATE public.households SET carer_person_id = 1 WHERE id = 1;

INSERT INTO public.comm_preferences (person_id, email_on, sms_on, whatsapp_on, opt_out_token)
VALUES
    (1, TRUE, FALSE, FALSE, 'demo-opt-out-1'),
    (2, TRUE, FALSE, FALSE, 'demo-opt-out-2'),
    (3, TRUE, FALSE, FALSE, 'demo-opt-out-3'),
    (4, TRUE, FALSE, FALSE, 'demo-opt-out-4'),
    (5, TRUE, FALSE, FALSE, 'demo-opt-out-5')
ON CONFLICT (person_id) DO NOTHING;

INSERT INTO public.activities
    (id, title, description, goal, age_band, day, support_need, language, capacity, spots_left, location)
VALUES
    (1, 'Swim - beginners', 'San Po Kong pool - ages 6-12 - bilingual coaches.', 'sport', 'child', 'saturday', 'low', 'both', 12, 2, 'San Po Kong'),
    (2, 'One-on-one nutrition', 'Cantonese sessions - teens - waitlist open.', 'nutrition', 'teen', 'weekday', '1to1', 'yue', 4, 0, 'San Po Kong'),
    (3, 'Yoga & stretch', 'Adult members - calm room - group welcome.', 'arts', 'adult', 'sunday', 'group', 'en', 15, 8, 'San Po Kong'),
    (4, 'Parent counselling circle', 'Carers peer support - monthly - San Po Kong.', 'family', 'adult', 'saturday', 'group', 'yue', 20, 11, 'San Po Kong'),
    (5, 'Ball sports clinic', 'Teens - bilingual - join waitlist for next block.', 'sport', 'teen', 'weekday', 'group', 'both', 10, 0, 'San Po Kong'),
    (6, 'Cooking together', 'Member-led kitchen - English - quiet hour option.', 'nutrition', 'adult', 'saturday', 'low', 'en', 8, 3, 'San Po Kong')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.registrations
    (id, activity_id, household_id, member_person_id, status, waitlist_position, reminder_channel, session_date, feedback)
VALUES
    (1, 1, 1, 2, 'registered', NULL, 'email', CURRENT_DATE + 7, NULL),
    (2, 2, 1, 2, 'waitlist', 4, 'email', CURRENT_DATE + 10, NULL),
    (3, 6, 1, 2, 'attended', NULL, 'email', CURRENT_DATE - 7, 'Alex loved the quiet hour and helped plate snacks.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.achievements
    (id, member_person_id, title, pillar, status, share_consent, coach_name, approved_at, created_at)
VALUES
    (1, 2, 'First 25m freestyle', 'sport', 'coach_approved', TRUE, 'Coach Pat', NOW() - INTERVAL '40 days', NOW() - INTERVAL '40 days'),
    (2, 2, 'Nutrition plan - 8 weeks', 'nutrition', 'coach_approved', FALSE, 'Coach Yan', NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.goals (id, member_person_id, title, status, target_date)
VALUES (1, 2, 'Lead warm-up - Sep goal', 'in_progress', DATE '2026-09-30')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.donation_commitments
    (id, supporter_person_id, amount_hkd, fund_category, status, cadence)
VALUES (1, 4, 300.00, 'Sports programmes', 'active', 'monthly')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.donation_receipts
    (id, commitment_id, amount_hkd, paid_at, story_back)
VALUES
    (1, 1, 300.00, NOW() - INTERVAL '20 days', 'Your donation of HKD 300 allowed us to fund two coach-led swim sessions, cover lane fees, and print bilingual class sheets.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.impact_badges (id, person_id, title, level, earned_at)
VALUES (1, 4, 'Local contributor', 'bronze', NOW() - INTERVAL '20 days')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.volunteer_profiles
    (id, person_id, skills, languages, availability, onboarded, hours_logged, points_balance, points_spent)
VALUES
    (1, 5, 'cantonese,photos,voice', 'yue,en', 'saturday mornings, remote', TRUE, 6.50, 55, 0),
    (2, 1, 'photos,voice', 'both', 'weekday evenings', TRUE, 1.00, 0, 0),
    (3, 4, 'photos', 'en', 'remote', FALSE, 0.00, 0, 0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.volunteer_shifts
    (id, title, description, duration_min, skills_needed, language, remote, spots_left, requires_onboarding, scheduled_date)
VALUES
    (1, 'Cantonese flyer check', 'Proofread banquet flyers.', 15, 'cantonese', 'yue', TRUE, 2, FALSE, CURRENT_DATE + 2),
    (2, 'Photo sort', 'Sort July hike photos into swim, kitchen, and track folders.', 30, 'photos', 'en', TRUE, 1, FALSE, CURRENT_DATE + 6),
    (3, 'Voice cheers', 'Record a few short cheers for Saturday track.', 45, 'voice', 'en', TRUE, 4, FALSE, CURRENT_DATE + 9),
    (4, 'Session buddy - swimming', 'Help one swim lane. Onboarded volunteers only.', 120, 'sports', 'both', FALSE, 2, TRUE, CURRENT_DATE + 12)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.volunteer_shift_claims
    (id, shift_id, volunteer_profile_id, status, hours, reflection, completed_at, points_awarded)
VALUES
    (1, 1, 1, 'completed', 0.25, 'Quick. Flyers look clearer in Cantonese.', NOW() - INTERVAL '18 days', 20),
    (2, 2, 1, 'completed', 0.50, 'Sorted hiking set; tagged for social wall.', NOW() - INTERVAL '10 days', 35),
    (3, 3, 1, 'claimed', 0.75, NULL, NULL, 0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.journey_events
    (id, person_id, event_type, channel, payload, created_at)
VALUES
    (1, 1, 'registration_confirmed', 'email', 'Swim - beginners', NOW() - INTERVAL '12 days'),
    (2, 1, 'waitlist_joined', 'email', 'One-on-one nutrition', NOW() - INTERVAL '5 days'),
    (3, 4, 'commitment_started', 'email', 'amount=300;fund=Sports programmes', NOW() - INTERVAL '20 days'),
    (4, 5, 'shift_completed', 'email', 'Cantonese flyer check', NOW() - INTERVAL '18 days')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.households', 'id'), COALESCE((SELECT MAX(id) FROM public.households), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.people', 'id'), COALESCE((SELECT MAX(id) FROM public.people), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.comm_preferences', 'id'), COALESCE((SELECT MAX(id) FROM public.comm_preferences), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.activities', 'id'), COALESCE((SELECT MAX(id) FROM public.activities), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.registrations', 'id'), COALESCE((SELECT MAX(id) FROM public.registrations), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.achievements', 'id'), COALESCE((SELECT MAX(id) FROM public.achievements), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.goals', 'id'), COALESCE((SELECT MAX(id) FROM public.goals), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.donation_commitments', 'id'), COALESCE((SELECT MAX(id) FROM public.donation_commitments), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.donation_receipts', 'id'), COALESCE((SELECT MAX(id) FROM public.donation_receipts), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.impact_badges', 'id'), COALESCE((SELECT MAX(id) FROM public.impact_badges), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.volunteer_profiles', 'id'), COALESCE((SELECT MAX(id) FROM public.volunteer_profiles), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.volunteer_shifts', 'id'), COALESCE((SELECT MAX(id) FROM public.volunteer_shifts), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.volunteer_shift_claims', 'id'), COALESCE((SELECT MAX(id) FROM public.volunteer_shift_claims), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.hire_enquiries', 'id'), COALESCE((SELECT MAX(id) FROM public.hire_enquiries), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.journey_events', 'id'), COALESCE((SELECT MAX(id) FROM public.journey_events), 1), TRUE);
